id: P010657
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:18:32.437210
source_metadata:
  id: bdr:W8LS16740
  title: བསྡུས་གཞུང་རིག་པའི་སྒོ་འབྱེད།
  author: ''
  volumes:
    6e433274fc5c418dbd391eeaa6489d8b:
      image_group_id: I8LS16749
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
