id: I6CEEAE9C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T01:30:43+00:00'
last_modified: '2022-06-08T16:33:49.447468+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16740
  title: བསྡུས་གཞུང་རིག་པའི་སྒོ་འབྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BB52:
      image_group_id: I8LS16749
      title: ''
      total_pages: 66
      order: 1
      base_file: BB52.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
